### ISSUE TITLE
URLs with single quote ' inside (allowed per RFC 3986) got 404

### ISSUE THREAD

**Issue by ache** [mnot/redbot#150]
Even if it is replaces with %27. Please fix.

**Comment by mnot** [comment]
Sample URL?

**Comment by ache** [comment]
http://art.vniz.net/giger/.cache/Giger-Alien%27s_cockpit.jpg.jpeg

**Comment by ache** [comment]
The root of the problem is that you encode % instead of decode it as all browsers does, so %27 turns into %2527 instead of '

**Comment by mnot** [comment]
Works for me; e.g.,

  https://redbot.org/?uri=http%3A//test.mnot.net/a/foo%27bar.txt

If you still encounter it, please reopen (and sorry for the extreme delay).

**Comment by ache** [comment]
Well, I have correct HTTP response code now, but right columns says:
`General`
`   The URI's syntax isn't valid.`
with the reference to RFC 3986 (which says that "'" is valid as belonging to sub-delims).
Example URL looks not like yours:
https://redbot.org/?uri=https%3A%2F%2Fart.vniz.net%2Fen%2Fgiger%2FGiger-Alien%2527s_cockpit.html
notice %25%27 here instead of just "'". All I do is copy and paste this URL in Firefox. In original Firefox window this URL is pasted from just single "'" is displayed.

**Comment by mnot** [comment]
Aha! Thanks for that. It should work now.

**Comment by ache** [comment]
Thanx, it works now.
BTW, I notice some Firefox/JS related bugs on the second page. While "add a request header" works on the very first page of your redbot site, it does nothing on the second (with request results). Pressing "view body", "view har" and "save" does nothing on the second page too. I surely remember they works long time ago. FF 49.0 Win. I start FF with clean profile to be sure that no addons involved.

**Comment by mnot** [comment]
Thanks, will have a look.

**Comment by ache** [comment]
I get this error in Console:
SyntaxError: JSON.parse: unterminated string at line 1 column 62 of the JSON data

**Comment by ache** [comment]
It seems "'" in the URL produce unterminated string.

**Comment by mnot** [comment]
Try now.

**Comment by ache** [comment]
It is better now, all works on the second page excepting 'view har' (still does nothing).
Thanx.

**Comment by mnot** [comment]
HAR should be fixed now. Thanks for the report(s)!

**Comment by ache** [comment]
Har is not fixed for all cases. Consider typing
`http://test.mnot.net/a/foo'bar.txt`
directly in the second page or pasting it as text (not pasting from the browser's address bar, browser really replaces "'" with %27 for its address bar copying). Resulting har URL is tail-stripped right on the quote:
`https://redbot.org/?id=KcPck6&req_hdr=User-Agent%3ARED/1%20(https://redbot.org/)&req_hdr=Referer%3Ahttp://test.mnot.net/a/foo`
and no har is shown.

**Comment by mnot** [comment]
OK, try now.

**Comment by ache** [comment]
All works in my testing, thanx!

**Comment by mnot** [comment]
Thanks for your patience!
